services:
  - type: web
    name: cinema-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DATABASE_URL
        value: "postgres://username:password@hostname:5432/dbname"  # Render Postgres
      - key: DEFAULT_SUPERUSER
        value: admin
      - key: DEFAULT_SUPERPASS
        value: admin123
      - key: DEFAULT_SUPEREMAIL
        value: admin@example.com
